In [114]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

In [115]:
df = pd.read_csv("../data/processed/processed_telco.csv")

df.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check,Churn_Yes
0,0,1,29.85,29.85,0,1,0,0,1,0,...,0,0,0,0,0,1,0,1,0,0
1,0,34,56.95,1889.50,1,0,0,1,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,2,53.85,108.15,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,1,1
3,0,45,42.30,1840.75,1,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
4,0,2,70.70,151.65,0,0,0,1,0,0,...,0,0,0,0,0,1,0,1,0,1

In [116]:
X = df.drop("Churn_Yes", axis=1)

y = df["Churn_Yes"]

In [117]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [118]:
print(X_train.shape)
print(X_test.shape)

(5625, 30)
(1407, 30)

#  Logistic Regression

In [119]:
from sklearn.preprocessing import StandardScaler

In [120]:
scaler = StandardScaler()

numeric_cols = ["tenure", "MonthlyCharges", "TotalCharges"]

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])

X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

In [121]:
log_model = LogisticRegression(max_iter=1000)

In [122]:
log_model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [123]:
y_pred = log_model.predict(X_test)

In [124]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.7867803837953091

In [125]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[915 118]
 [182 192]]

In [126]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1033
           1       0.62      0.51      0.56       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [127]:
roc = roc_auc_score(y_test, y_pred)

print("ROC-AUC Score:", roc)

ROC-AUC Score: 0.6995692935274965

In [128]:
log_precision = precision_score(y_test, y_pred)
log_recall = recall_score(y_test, y_pred)
log_f1 = f1_score(y_test, y_pred)

# Descision Tree

In [129]:
dt_model = DecisionTreeClassifier(
    random_state=42
)

In [130]:
dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [131]:
dt_pred = dt_model.predict(X_test)

In [132]:
dt_accuracy = accuracy_score(y_test, dt_pred)

print("Decision Tree Accuracy:", dt_accuracy)

Decision Tree Accuracy: 0.7256574271499645

In [133]:
print(confusion_matrix(y_test, dt_pred))

[[824 209]
 [177 197]]

In [134]:
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81      1033
           1       0.49      0.53      0.51       374

    accuracy                           0.73      1407
   macro avg       0.65      0.66      0.66      1407
weighted avg       0.73      0.73      0.73      1407

In [135]:
dt_roc = roc_auc_score(y_test, dt_pred)

print("Decision Tree ROC-AUC:", dt_roc)

Decision Tree ROC-AUC: 0.6622073189039763

In [136]:
dt_precision = precision_score(y_test, dt_pred)
dt_recall = recall_score(y_test, dt_pred)
dt_f1 = f1_score(y_test, dt_pred)

# Random Forest

In [137]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [138]:
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [139]:
rf_pred = rf_model.predict(X_test)

In [140]:
rf_accuracy = accuracy_score(y_test, rf_pred)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.7846481876332623

In [141]:
print(confusion_matrix(y_test, rf_pred))

[[927 106]
 [197 177]]

In [142]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1033
           1       0.63      0.47      0.54       374

    accuracy                           0.78      1407
   macro avg       0.73      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407

In [143]:
rf_roc = roc_auc_score(y_test, rf_pred)

print("Random Forest ROC-AUC:", rf_roc)

Random Forest ROC-AUC: 0.6853241428578823

In [144]:
rf_precision = precision_score(y_test, rf_pred)
rf_recall = recall_score(y_test, rf_pred)
rf_f1 = f1_score(y_test, rf_pred)

# XGBOOST

In [145]:
xgb_model = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

In [146]:
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, ...)

In [147]:
xgb_pred = xgb_model.predict(X_test)

In [148]:
xgb_accuracy = accuracy_score(y_test, xgb_pred)

print("XGBoost Accuracy:", xgb_accuracy)

XGBoost Accuracy: 0.7683013503909026

In [149]:
print(confusion_matrix(y_test, xgb_pred))

[[903 130]
 [196 178]]

In [150]:
print(classification_report(y_test, xgb_pred))

              precision    recall  f1-score   support

           0       0.82      0.87      0.85      1033
           1       0.58      0.48      0.52       374

    accuracy                           0.77      1407
   macro avg       0.70      0.68      0.68      1407
weighted avg       0.76      0.77      0.76      1407

In [151]:
xgb_roc = roc_auc_score(y_test, xgb_pred)

print("XGBoost ROC-AUC:", xgb_roc)

XGBoost ROC-AUC: 0.6750443907211745

In [152]:
xgb_precision = precision_score(y_test, xgb_pred)
xgb_recall = recall_score(y_test, xgb_pred)
xgb_f1 = f1_score(y_test, xgb_pred)

# Model Comparison

In [153]:
comparison = pd.DataFrame({

    "Model":[
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "XGBoost"
    ],

    "Accuracy":[
        accuracy,
        dt_accuracy,
        rf_accuracy,
        xgb_accuracy
    ],

    "Precision":[
        log_precision,
        dt_precision,
        rf_precision,
        xgb_precision
    ],

    "Recall":[
        log_recall,
        dt_recall,
        rf_recall,
        xgb_recall
    ],

    "F1 Score":[
        log_f1,
        dt_f1,
        rf_f1,
        xgb_f1
    ],

    "ROC-AUC":[
        roc,
        dt_roc,
        rf_roc,
        xgb_roc
    ]

})

comparison.round(3)

                 Model  Accuracy  Precision  Recall  F1 Score  ROC-AUC
0  Logistic Regression     0.787      0.619   0.513     0.561    0.700
1        Decision Tree     0.726      0.485   0.527     0.505    0.662
2        Random Forest     0.785      0.625   0.473     0.539    0.685
3              XGBoost     0.768      0.578   0.476     0.522    0.675

# Best Model Selection

In [154]:
best_model = comparison.sort_values(
    by="ROC-AUC",
    ascending=False
)

best_model

                 Model  Accuracy  Precision    Recall  F1 Score   ROC-AUC
0  Logistic Regression  0.786780   0.619355  0.513369  0.561404  0.699569
2        Random Forest  0.784648   0.625442  0.473262  0.538813  0.685324
3              XGBoost  0.768301   0.577922  0.475936  0.521994  0.675044
1        Decision Tree  0.725657   0.485222  0.526738  0.505128  0.662207

## Conclusion

Four machine learning models were trained and evaluated:

- Logistic Regression
- Decision Tree
- Random Forest
- XGBoost

Models were compared using:

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

The model with the highest ROC-AUC was selected as the final model for deployment and explanation using SHAP.

## Final Model Selection

Based on the evaluation metrics (Accuracy, Precision, Recall, F1 Score, and ROC-AUC), Logistic Regression achieved the best overall performance.

Although Random Forest and XGBoost are more complex ensemble models, Logistic Regression provided the highest ROC-AUC and the best balance between precision and recall.

Therefore, Logistic Regression was selected as the final model for interpretation using SHAP and deployment in the Streamlit application.

In [155]:
import joblib

In [156]:
final_model = log_model

In [157]:
joblib.dump(final_model, "../models/churn_model.pkl")

['../models/churn_model.pkl']

In [158]:
joblib.dump(scaler, "../models/scaler.pkl")

['../models/scaler.pkl']

In [159]:
joblib.dump(X.columns.tolist(), "../models/feature_names.pkl")

['../models/feature_names.pkl']